[project]
name = "nolqr"
version = "20241014"
description = "QR code generation lighter than an unladen swallow."
readme = "README.md"
license = "MIT"
keywords = [ "qr" ]
classifiers = [ "Topic :: Utilities" ]

authors = [
  {name = "Jelmer van Arnhem"},
]
maintainers = [
  {name = "Giovanni Garciliano", email = "hola@campanita.org"}
]
